# Generated by Django 3.2.4 on 2021-06-08 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=40)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=20)),
                ('cidade', models.CharField(max_length=20)),
                ('uf', models.CharField(max_length=2)),
                ('cep', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('telefone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.endereco')),
            ],
        ),
    ]
