# Generated by Django 3.2.4 on 2021-06-10 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('CNPJ', models.BigIntegerField()),
                ('telefone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.endereco')),
            ],
        ),
    ]
