# Generated by Django 3.2.4 on 2021-06-11 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_compromisso'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromisso',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.cliente'),
            preserve_default=False,
        ),
    ]
