# Generated by Django 3.2.4 on 2021-06-20 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_compromisso_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContasaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vencimento', models.DateField()),
                ('valor', models.FloatField()),
                ('situacao', models.CharField(choices=[('1', 'A vencer'), ('2', 'Vencido'), ('3', 'Protestado'), ('4', 'Pago até o vencimento'), ('5', 'Regularizado')], default='1', max_length=25)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ContasaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vencimento', models.DateField()),
                ('valor', models.FloatField()),
                ('situacao', models.CharField(choices=[('1', 'A vencer'), ('2', 'Vencido'), ('3', 'Protestado'), ('4', 'Pago até o vencimento'), ('5', 'Regularizado')], default='1', max_length=25)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fornecedor')),
            ],
        ),
    ]
