# Generated by Django 3.2.4 on 2021-06-21 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210620_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='fornecedor',
            field=models.ManyToManyField(to='app.Fornecedor'),
        ),
    ]
