# Generated by Django 3.2.4 on 2021-06-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_notafiscal_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromisso',
            name='tipo',
            field=models.CharField(choices=[('0', 'Visita técnica'), ('1', 'Reparo em portões'), ('2', 'Reparo em rede elétrica'), ('3', 'Instalação de câmeras')], default='0', max_length=30),
            preserve_default=False,
        ),
    ]
