# Generated by Django 3.2.4 on 2021-06-26 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_compromisso_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notafiscal',
            name='fornecedor',
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='fornecedor',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app.fornecedor'),
            preserve_default=False,
        ),
    ]
