# Generated by Django 3.2.6 on 2021-08-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210626_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromisso',
            name='identificador',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
