# Generated by Django 3.2.6 on 2021-08-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_equipamentos_insumos'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromisso',
            name='equipamentos',
            field=models.ManyToManyField(to='app.Equipamentos'),
        ),
    ]
